// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjorejllbfsvlffldgce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlqb3JlamxsYmZzdmxmZmxkZ2NlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMzc5NTgsImV4cCI6MjA2MTgxMzk1OH0.N7igj8bbQwoE-6CcHl15RWqeHTurOK6IsH9gsFc-_gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);